# Quickstart tutorial

## The basics

In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.shape

(3, 5)

In [5]:
a.ndim

2

In [6]:
a.dtype

dtype('int32')

In [8]:
a.itemsize # 每个元素字节大小

4

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
a=np.array([1,2,3,4])

In [12]:
a

array([1, 2, 3, 4])

In [13]:
b=np.array([[1,2,4],[4,5,6]])

In [14]:
b

array([[1, 2, 4],
       [4, 5, 6]])

In [15]:
b=np.array([[1,2,4],[4,5,6]],dtype=complex)

In [16]:
b

array([[ 1.+0.j,  2.+0.j,  4.+0.j],
       [ 4.+0.j,  5.+0.j,  6.+0.j]])

In [17]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [18]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [19]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [21]:
np.linspace(10,30,5)

array([ 10.,  15.,  20.,  25.,  30.])

### np.fromfucntion

In [26]:
np.fromfunction(lambda i,j : i == j,(3,3),dtype=int)# j,j代表坐标索引

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]], dtype=bool)

In [25]:
np.fromfunction(lambda i,j : i+j,(4,4),dtype=int)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

### 矩阵计算

In [27]:
A=np.array([[1,1],
            [0,1]])

In [28]:
B=np.array([[2,0],
            [3,4]])

In [30]:
A*B#对应元素相乘

array([[2, 0],
       [0, 4]])

In [31]:
A.dot(B)#点乘

array([[5, 4],
       [3, 4]])

In [32]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

### np.all

In [33]:
np.all([[True,True],[False,True]])

False

In [34]:
np.all([[True,True],[False,True]],axis=0)

array([False,  True], dtype=bool)

In [35]:
np.all([[True,True],[False,True]],axis=1)

array([ True, False], dtype=bool)

In [36]:
np.all([-1,4,5])

True

In [37]:
np.all([0,4])

False

In [38]:
np.all([1,np.nan])

True

### np.apply_along_axis

In [39]:
def my_func(a):
    return (a[0]+a[-1])*0.5

In [40]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [41]:
np.apply_along_axis(my_func,0,b)

array([ 4.,  5.,  6.])

In [43]:
np.apply_along_axis(my_func,1,b)

array([ 2.,  5.,  8.])

### np.bincount()

bin的数量比x中的最大值大1，每个bin给出了它的索引值在x中出现的次数。

In [45]:
# 我们可以看到x中最大的数为7，因此bin的数量为8，那么它的索引值为0->7
x = np.array([0, 1, 1, 3, 2, 1, 7])

In [47]:
# 索引0出现了1次，索引1出现了3次......索引5出现了0次......
np.bincount(x)

array([1, 3, 1, 1, 0, 0, 0, 1], dtype=int64)

In [49]:
x = np.array([7, 6, 2, 1, 4])
np.bincount(x)

array([0, 1, 1, 0, 1, 0, 1, 1], dtype=int64)

下面，我来解释一下weights这个参数。文档说，如果weights参数被指定，那么x会被它加权，也就是说，如果值n发现在位置i，那么out[n] += weight[i]而不是out[n] += 1.因此，我们weights的大小必须与x相同，否则报错。下面，我举个例子让大家更好的理解一下：

In [50]:
w = np.array([0.3, 0.5, 0.2, 0.7, 1., -0.6])
# 我们可以看到x中最大的数为4，因此bin的数量为5，那么它的索引值为0->4
x = np.array([2, 1, 3, 4, 4, 3])
# 索引0 -> 0
# 索引1 -> w[1] = 0.5
# 索引2 -> w[0] = 0.3
# 索引3 -> w[2] + w[5] = 0.2 - 0.6 = -0.4
# 索引4 -> w[3] + w[4] = 0.7 + 1 = 1.7
np.bincount(x,  weights=w)
# 因此，输出结果为：array([ 0. ,  0.5,  0.3, -0.4,  1.7])

array([ 0. ,  0.5,  0.3, -0.4,  1.7])

最后，我们来看一下minlength这个参数。文档说，如果minlength被指定，那么输出数组中bin的数量至少为它指定的数（如果必要的话，bin的数量会更大，这取决于x）。下面，我举个例子让大家更好的理解一下：

In [51]:
# 我们可以看到x中最大的数为3，因此bin的数量为4，那么它的索引值为0->3
x = np.array([3, 2, 1, 3, 1])
# 本来bin的数量为4，现在我们指定了参数为7，因此现在bin的数量为7，所以现在它的索引值为0->6
np.bincount(x, minlength=7)
# 因此，输出结果为：array([0, 2, 1, 2, 0, 0, 0])

array([0, 2, 1, 2, 0, 0, 0], dtype=int64)

In [53]:
# 我们可以看到x中最大的数为3，因此bin的数量为4，那么它的索引值为0->3
x = np.array([3, 2, 1, 3, 1])
# 本来bin的数量为4，现在我们指定了参数为1，那么它指定的数量小于原本的数量，
# 因此这个参数失去了作用，索引值还是0->3
np.bincount(x, minlength=1)
# 因此，输出结果为：array([0, 2, 1, 2])

array([0, 2, 1, 2], dtype=int64)

### np.clip

In [54]:
a = np.arange(10)

In [55]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.clip(a,3,6)

array([3, 3, 3, 3, 4, 5, 6, 6, 6, 6])

### np.conj

返回共轭

In [57]:
np.conj(1+2j)

(1-2j)

### np.corrcoef

返回相关系数

In [60]:
np.corrcoef([[1,2,3,7],[1,2,3,5],[2,4,6,3]])

array([[ 1.        ,  0.98333795,  0.01855355],
       [ 0.98333795,  1.        ,  0.2       ],
       [ 0.01855355,  0.2       ,  1.        ]])

### np.cov
返回协方差

### np.cross
返回两个矢量的叉积

In [61]:
x = [1,2,3]

In [62]:
y = [4,5,6]

In [63]:
np.cross(x,y)

array([-3,  6, -3])

In [64]:
x = [1,2]
y = [4,5,6]
z = [1,2,0]

In [65]:
np.cross(x,y)

array([12, -6, -3])

In [66]:
np.cross(z,y)

array([12, -6, -3])

In [67]:
x = [1,2]
y = [3,5]

In [68]:
np.cross(x,y)

array(-1)

### np.diff

In [69]:
x = np.array([1,2,4,7,0])

In [70]:
np.diff(x)

array([ 1,  2,  3, -7])

In [71]:
x = np.array([[1, 3, 6, 10], [0, 5, 6, 8]])

In [72]:
x

array([[ 1,  3,  6, 10],
       [ 0,  5,  6,  8]])

In [73]:
np.diff(x)

array([[2, 3, 4],
       [5, 1, 2]])

In [74]:
np.diff(x, axis=0)

array([[-1,  2,  0, -2]])

In [75]:
np.diff(x, axis=1)

array([[2, 3, 4],
       [5, 1, 2]])

### np.inner
两个阵列的内积

In [77]:
a = np.array([1,2,3])

In [78]:
b = np.array([2,4,6])

In [79]:
np.inner(a,b)

28

In [81]:
a = np.arange(24).reshape(4,6)

In [82]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [89]:
b = np.array([1,0,0,0,0,2])

In [90]:
np.inner(a,b)

array([10, 28, 46, 64])

In [91]:
np.inner(np.eye(2),7)

array([[ 7.,  0.],
       [ 0.,  7.]])

### np.maximum

In [92]:
np.maximum([2,3,4],[1,5,2])

array([2, 5, 4])

In [93]:
x = np.arange(4).reshape(2,2)

In [94]:
x

array([[0, 1],
       [2, 3]])

In [95]:
np.maximum(x,[1,2])

array([[1, 2],
       [2, 3]])

### np.nonzero()
返回非零元素的索引

In [96]:
x = np.array([[1,0,2], [0,2,0], [1,1,0]])

In [97]:
x

array([[1, 0, 2],
       [0, 2, 0],
       [1, 1, 0]])

In [99]:
np.nonzero(x)# 返回两个数组，结合起来就是索引

(array([0, 0, 1, 2, 2], dtype=int64), array([0, 2, 1, 0, 1], dtype=int64))

### np.outer()
计算外积,outer是a的第一个元素跟b的每一个元素相乘作为第一行，第二个元素跟b的每一个元素相乘作为第二个元素...
一半outer()用的很少

In [100]:
x = np.array([1,2,3])

In [101]:
y = np.array([4,5,6])

In [102]:
np.outer(x,y)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

### np.prod
返回给定轴上的数组元素的乘积。未给轴，则返回所有

In [103]:
np.prod([1,2])

2

In [106]:
np.prod([[1,2],[3,4]])

24

In [107]:
np.prod([[1.,2.],[3.,4.]], axis=1)

array([  2.,  12.])

In [108]:
np.prod([[1.,2.],[3.,4.]], axis=0)

array([ 3.,  8.])

### np.trace()
返回迹

In [110]:
np.trace(np.eye(3))

3.0

In [111]:
a = np.arange(8).reshape((2,2,2))

In [113]:
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [112]:
np.trace(a)

array([6, 8])

In [114]:
a = np.arange(24).reshape((2,2,2,3))

In [115]:
a

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [116]:
np.trace(a)

array([[18, 20, 22],
       [24, 26, 28]])

### np.transpose()
转置矩阵

### numpy.vdot
复数矩阵的点乘

In [117]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])

In [118]:
np.vdot(a, b)

(70-8j)

### numpy.vectorize

In [119]:
def myfunc(a, b):
    "Return a-b if a>b, otherwise return a+b"
    if a > b:
        return a - b
    else:
        return a + b

In [120]:
vfunc = np.vectorize(myfunc)

In [121]:
vfunc([1, 2, 3, 4], 2)

array([3, 4, 1, 2])

In [122]:
vfunc.__doc__

'Return a-b if a>b, otherwise return a+b'